#!/usr/bin/python

import os, subprocess, sys
from optparse import OptionParser

parser = OptionParser(usage="usage: %prog /path/to/riscv_asm input [output]")
(options,args) = parser.parse_args()

if len(args)!=2 and len(args)!=3:
    parser.error("Wrong number of args.")

riscv_asm = args[0]
riscv_file = args[1]

current_dir = os.getcwd() + '/'
file_path = current_dir + riscv_file
file_exists = os.path.isfile(file_path)

if not file_exists:
    print 'File not found.'
    sys.exit(1)

out_file_name = file_path.split('/')[-1].split('.')[0] + '.x'

p = subprocess.Popen([riscv_asm, "-aln", "-march=rv32i", "-W", file_path, "-o riscv_temp.out"], stdout=subprocess.PIPE)

out, err = p.communicate()

q = subprocess.Popen(["rm", current_dir + ' riscv_temp.out'], stderr=subprocess.PIPE)

q.communicate()

hex_out = ''

for lines in out.split('\n'):
    current_line = lines.split('\t')[0].strip().split(' ')
    if len(current_line) > 1:
#        hex_out += current_line[2] + '\n'
        byte1 = current_line[2][0:2]
        byte2 = current_line[2][2:4]
        byte3 = current_line[2][4:6]
        byte4 = current_line[2][6:8]
        hex_out += byte4 + byte3 + byte2 + byte1 + '\n'


if len(args)==3:
  out_file_name=args[2]
else:
  out_file_name = file_path[:len(file_path)-len(file_path.split('/')[-1])] + out_file_name

out_file = open(out_file_name,'w+')
out_file.write(hex_out)
out_file.close()

