set init_layout_view ""
set init_abstract_name ""
set init_verilog "/home/rjridle/risc-v-chisel/fabcds20/synth/mapped/riscv.vh"
set init_mmmc_file "/home/rjridle/risc-v-chisel/fabcds20/par/FF/view_definition.tcl"
set init_lef_file "/home/rjridle/osugooglelib/outputs/s8_osu130.lef"
set init_top_cell "/home/rjridle/risc-v-chisel/fabcds20/par/riscv"
set init_gnd_net "VSS"
set init_pwr_net "VDD"
